AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Invoked via API Gateway, pushes messages to sqs for all slack channels to be imported for entity'

Resources:
    initiateSlackImport:
        Type: 'AWS::Serverless::Function'
        Properties:
            Handler: handler.handler
            Runtime: nodejs20.x
            CodeUri: ./dist
            Timeout: 600
            Events:
