AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Gmail batch import SQS message queue handler'

Resources:
    batchGmailDrive:
        Type: 'AWS::Serverless::Function'
        Properties:
            Handler: batchGmailDrive/src/handler.handler
            Runtime: nodejs20.x
            CodeUri: ./dist
            Timeout: 600
            Events:
                GmailImportMessage:
                    Type: SQS
                    Properties:
                        Queue: arn:aws:sqs:us-east-1:353643225333:GmailBatchImportQueue.fifo
