AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Google cal batch import SQS message queue handler'

Resources:
    batchImportGoogleCal:
        Type: 'AWS::Serverless::Function'
        Properties:
            Handler: batchImportGoogleCal/src/handler.handler
            Runtime: nodejs20.x
            CodeUri: ./dist
            Timeout: 600
            Events:
                GoogleCalImportMessage:
                    Type: SQS
                    Properties:
                        Queue: arn:aws:sqs:us-east-1:353643225333:GoogleCalBatchImportQueue.fifo
