/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: (typeof import('./components/AppFooter.vue'))['default']
    HelloWorld: (typeof import('./components/HelloWorld.vue'))['default']
    HorizontalLine: typeof import('./components/common/HorizontalLine.vue')['default']
    NavOpenClose: typeof import('./components/customIcons/NavOpenClose.vue')['default']
    NewChatInfoBlock: typeof import('./components/chat/NewChatInfoBlock.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNav: typeof import('./components/SideNav.vue')['default']
    UserAvatar: typeof import('./components/common/UserAvatar.vue')['default']
  }
}
