AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Invoked via API Gateway, pushes messages to sqs for all google drive docs to be imported for entity'

Resources:
    initiateGoogleDriveImport:
        Type: 'AWS::Serverless::Function'
        Properties:
            Handler: initiateGoogleDriveImport/src/handler.handler
            Runtime: nodejs20.x
            CodeUri: ./dist
            Timeout: 600
