AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Google meet batch import SQS message queue handler'

Resources:
    batchImportGoogleMeet:
        Type: 'AWS::Serverless::Function'
        Properties:
            Handler: batchImportGoogleMeet/src/handler.handler
            Runtime: nodejs20.x
            CodeUri: ./dist
            Timeout: 600
            Events:
                GoogleMeetImportMessage:
                    Type: SQS
                    Properties:
                        Queue: arn:aws:sqs:us-east-1:353643225333:GoogleMeetBatchImportQueue.fifo
